services:
  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: cleverdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: